# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.mandelbrot <- function(dim = 500L, maxIter = 256L, R = 1.0, cx = 0.0, cy = 0.0, exponent = 2.0, escape = 0.0) {
    .Call('_fractal_mandelbrot', PACKAGE = 'fractal', dim, maxIter, R, cx, cy, exponent, escape)
}

.julia <- function(c, dim = 500L, maxIter = 256L, R = 0.0, cx = 0.0, cy = 0.0, exponent = 2.0, escape = 0.0) {
    .Call('_fractal_julia', PACKAGE = 'fractal', c, dim, maxIter, R, cx, cy, exponent, escape)
}

